trigger:
- main
pool:
  vmImage: ubuntu-latest
steps:
  - task: configuration@1
    inputs:
      connection: 'ritam_test'
      isTunnelActivate: false
      isAppAutomate: false
      isSmartUI: false
  - script: |
      mvn clean install -DskipTests
  - script: "mvn test -D suite=single.xml"
    displayName: "Command Line Script"
  - task: LambdatestResults@1