trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndTest
  displayName: "Build and Test"
  jobs:
  - job: BuildAndTestJob
    displayName: "Build and Test Job"
    steps:
    - task: configuration@1
      displayName: "LambdaTest configuration setup"
      inputs:
        connection: ritam_test

    - script: |
        mvn clean install -DskipTests
      displayName: "Build Maven Project"

    - script: "mvn test -D suite=single.xml"
      displayName: "Run Tests"

- stage: LambdatestResults
  displayName: "LambdaTest Results"
  jobs:
  - job: LambdatestResultsJob
    displayName: "Lambdatest Results Job"
    steps:
    - task: LambdatestResults@1
      displayName: "Lambdatest Results Task"
