trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndTest
  jobs:
  - job: BuildAndTestJob
    steps:
    - task: configuration@1
      inputs:
        connection: 'ritam_test'
        isTunnelActivate: false
        isAppAutomate: true
        isSmartUI: false

    - script: |
        mvn clean install -DskipTests

    - script: |
        mvn test -D suite=single.xml
      displayName: "Command Line Script"
    - task: LambdatestResults@1

- stage: LambdatestResults
  jobs:
  - job: LambdatestResultsJob
    steps:
    - task: LambdatestResults@1
      # Configure inputs for the LambdatestResults task here