# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndTest
  jobs:
  - job: BuildAndTestJob
    steps:
    - task: configuration@1
      inputs:
        connection: 'ritam_test'
        isTunnelActivate: false
        isAppAutomate: true
        isSmartUI: false

    - script: |
        mvn clean install -DskipTests

    - script: |
        mvn test -D suite=single.xml
      displayName: "Command Line Script"

- stage: LambdatestResults
  jobs:
  - job: LambdatestResultsJob
    steps:
    - task: LambdatestResults@1
      # Configure inputs for the LambdatestResults task here




